<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Tsinswreng.CsTreeTest" Version="0.1.1-alpha" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Tsinswreng.Avln.Dsl\Tsinswreng.Avln.Dsl.csproj" />
	</ItemGroup>
</Project>
